
<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20

        Button:
            text: "Hello World!"

        Button:
            text: "Goodbye World!"

        Button:
            text: "Get High!"
            pos_hint: {"center_x": .5} # Possition in box 
            size_hint: (None, None) # Responsive (x,y) value between 0 and 1
            width: 200 # Hardcord values
            height: 50
